name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Image Name"
    required: false
    default: "academy"
  tag_name:
    description: "Image tag"
    required: false
    default: "$(date +%s)"

runs:
  using: composite
  steps:
    - name: define tag name
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
      shell: bash
    - name: defining image name
      run: echo "DOCKER_IMAGE_NAME=${{inputs.image_name}}":"${{env.TAG}}" >> $GITHUB_ENV
      shell: bash

    - run: |
        docker build . --file "${{inputs.dockerfile_path}}" --tag "${{env.DOCKER_IMAGE_NAME}}"
      shell: bash

    - name: check if docker is running
      run: docker images
      shell: bash

