name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: marsul1/academy/.github/actions/maven_build@main

    - uses: marsul1/academy/.github/actions/docker_build@main
      with:
        dockerfile_path: "src/main/docker/Dockerfile.jvm"

    - name: check if docker is running
      run: docker images

