name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: marsul1/academy/.github/actions/maven_build@main

    - uses: marsul1/academy/.github/actions/docker_build@main
      with:
        dockerfile_path: "src/main/docker/Dockerfile.jvm"
        image_name: marcoriofortes843/academy

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push to docker hub
      uses: marsul1/academy/.github/actions/docker_hub@main
      with:
        docker_image_name_username: ${{ env.DOCKER_IMAGE_NAME }}



